# Waypaper Floating & Centered Zen Rules
windowrulev2 = float, class:^(waypaper)$
windowrulev2 = center, class:^(waypaper)$
windowrulev2 = size 800 500, class:^(waypaper)$decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.9

    # Special workspace dimming & blur
    dim_special = 0.5
    
    blur {
        enabled = true
        size = 8
        passes = 2
        special = true    # Enables blur rendering behind special workspace
    }
}animations {
    enabled = yes

    # Add these lines for special workspace transitions
    animation = specialWorkspace, 1, 4, default, slidevert
}
exec-once = quickshell -c caelestia

# Waypaper Floating & Centered Zen Rules
windowrulev2 = float, class:^(waypaper)$
windowrulev2 = center, class:^(waypaper)$
windowrulev2 = size 800 500, class:^(waypaper)$
