-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        inactive_timeout = 5.0,
    },
    decoration = {
        blur = {
            size = 5,
        },
    },
    general = {
        gaps_in = 2,
        gaps_out = 0,
    },
    misc = {
        animate_mouse_windowdragging = false,
    },
})

-- Bezier curves
hl.curve("easeOutQuad", { type = "bezier", points = { {0.5, 1.0}, {0.89, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 3.5,
    bezier = "default",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 7.0,
    bezier = "default",
    style = "slidefade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 7.0,
    bezier = "default",
    style = "slidefade",
})
hl.animation({
    leaf = "specialWorkspaceIn",
    enabled = true,
    speed = 4.5,
    bezier = "easeOutQuad",
    style = "fade",
})
hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 4.5,
    bezier = "easeOutQuad",
    style = "fade",
})
